const categories = [
"Acute ischemic stroke thrombolysis",
"Endovascular thrombectomy / large vessel occlusion",
"Large core thrombectomy",
"Wake-up / unknown-onset stroke",
"Minor stroke / TIA / dual antiplatelet therapy",
"ESUS",
"Atrial fibrillation / anticoagulation",
"Carotid stenosis / carotid revascularization",
"Intracranial atherosclerosis",
"Intracerebral hemorrhage",
"Subarachnoid hemorrhage",
"Lipid therapy",
"Blood pressure management",
"PFO and cryptogenic stroke",
"Stroke systems of care",
"Other important trials"
];

function T(name, year, category, condition, intervention, topic, clinicalQuestion, population, comparator, sampleSize, primaryOutcome, mainResult, conclusion, rationale, criticism, limitations, practice, reference, aliases=[]){
  return {name,year,category,condition,intervention,topic,clinicalQuestion,population,comparator,sampleSize,primaryOutcome,mainResult,conclusion,rationale,criticism,limitations,practice,reference,aliases,status:"built-in landmark database"};
}
const verify="verify exact number";
const trials=[
T("NINDS rt-PA Trial","1995","Acute ischemic stroke thrombolysis","Acute ischemic stroke","IV alteplase","IV thrombolysis 0–3 h","Does IV alteplase improve outcome when given within 3 hours?","AIS within 3 hours with measurable deficit","Placebo","624","Disability/global outcome at 3 months","Improved odds of minimal/no disability despite increased symptomatic ICH.","Established alteplase as practice-changing acute stroke therapy.","Recanalization may salvage ischemic penumbra if given early.","Strict time window; baseline imbalances debated.","Selected population; hemorrhage risk; older imaging era.","Made emergency thrombolysis a core stroke-code treatment.","The NINDS rt-PA Stroke Study Group. N Engl J Med. 1995;333:1581-1587.",["NINDS","rt-PA","tPA"]),
T("ECASS I","1995","Acute ischemic stroke thrombolysis","Acute ischemic stroke","IV alteplase","IV thrombolysis","Tested alteplase in early AIS using European dosing/criteria.","AIS within 6 hours","Placebo",verify,"Functional outcome and safety","Did not show clear overall benefit; protocol violations and hemorrhage concerns.","Helped refine imaging exclusion and dosing standards.","Earlier reperfusion may improve outcome.","High hemorrhage risk with larger dose and CT protocol issues.","Protocol violations; broad time window.","Informed safer alteplase trial design.","Hacke et al. JAMA. 1995;274:1017-1025.",["ECASS 1"]),
T("ECASS II","1998","Acute ischemic stroke thrombolysis","Acute ischemic stroke","IV alteplase","IV thrombolysis","Does 0.9 mg/kg alteplase improve outcomes within 6 hours?","AIS within 6 hours","Placebo",verify,"mRS/disability","Primary endpoint neutral; secondary analyses suggested possible benefit.","Supported the importance of early treatment and safer dosing.","Reperfusion benefit depends on time and selection.","Outcome definitions and time window limited effect.","Not powered for modern subgroups.","Contributed to evidence base for thrombolysis.","Hacke et al. Lancet. 1998;352:1245-1251.",["ECASS 2"]),
T("ECASS III","2008","Acute ischemic stroke thrombolysis","Acute ischemic stroke","IV alteplase","Extended-window thrombolysis","Does alteplase help at 3 to 4.5 hours?","AIS treated 3–4.5 hours","Placebo","821","mRS 0–1 at 90 days","Improved favorable outcome with increased sICH but no significant mortality increase.","Extended alteplase eligibility to 4.5 hours in selected patients.","Some penumbra persists beyond 3 hours.","Exclusion criteria limit generalizability.","Benefit smaller than earlier treatment; controversy after reanalyses.","Supported 4.5-hour alteplase window.","Hacke et al. N Engl J Med. 2008;359:1317-1329.",["ECASS 3"]),
T("ATLANTIS","1999","Acute ischemic stroke thrombolysis","Acute ischemic stroke","IV alteplase","Extended-window thrombolysis","Does alteplase work in later time windows?","AIS mainly 3–5 hours","Placebo",verify,"Functional outcome","No clear benefit and increased hemorrhage in later window.","Emphasized time dependence of alteplase benefit.","Late reperfusion may be too late without imaging selection.","Later treatment and heterogeneous population.","Older imaging selection; limited modern applicability.","Reinforced urgency of treatment.","Clark et al. JAMA. 1999;282:2019-2026.",["ATLANTIS A","ATLANTIS B"]),
T("IST-3","2012","Acute ischemic stroke thrombolysis","Acute ischemic stroke","IV alteplase","IV thrombolysis broad eligibility","Can alteplase benefit broader/older patients within 6 hours?","Broad AIS population including elderly","Control","3035","Alive and independent at 6 months","Neutral primary dichotomous endpoint, but ordinal analyses supported benefit; early hemorrhage risk.","Supported use in selected older patients and broader evidence base.","Treatment effect may persist across age groups.","Open-label design; broad time window.","Outcome interpretation complex.","Helped reduce age-based exclusion.","Sandercock et al. Lancet. 2012;379:2352-2363.",["IST 3"]),
T("ENCHANTED","2016","Acute ischemic stroke thrombolysis","Acute ischemic stroke","Low-dose vs standard-dose alteplase","Thrombolytic dosing","Is low-dose alteplase noninferior to standard dose?","Alteplase-eligible AIS","Standard-dose alteplase","3310","Death or disability; sICH","Low dose did not meet noninferiority for efficacy but reduced sICH.","Standard-dose alteplase remained usual dose in many guidelines.","Lower dose may reduce bleeding but could reduce efficacy.","Noninferiority not met.","Regional practice variation; endpoint nuance.","Clarified alteplase dosing tradeoff.","Anderson et al. N Engl J Med. 2016;374:2313-2323.",[]),
T("NOR-TEST","2017","Acute ischemic stroke thrombolysis","Acute ischemic stroke","Tenecteplase 0.4 mg/kg","Thrombolytic choice","Is tenecteplase noninferior/safe compared with alteplase?","Mild AIS population common","Alteplase",verify,"Functional outcome","Showed similar outcomes, but many minor strokes and high TNK dose.","Informed TNK evidence but dose/population limitations matter.","Bolus tenecteplase is operationally attractive.","Mild stroke predominance; dose later questioned.","Limited power for severe LVO.","Contributed to TNK debate.","Logallo et al. Lancet Neurol. 2017;16:781-788.",["NOR TEST"]),
T("AcT Trial","2022","Acute ischemic stroke thrombolysis","Acute ischemic stroke","Tenecteplase 0.25 mg/kg","Thrombolytic choice","Is tenecteplase noninferior to alteplase for AIS?","Thrombolysis-eligible AIS","Alteplase","1600","mRS 0–1 at 90–120 days","Tenecteplase was noninferior to alteplase.","Supported TNK 0.25 mg/kg as practical alteplase alternative.","Single bolus improves workflow.","Open-label design.","Noninferiority trial; subgroup precision limited.","Helped guideline endorsement of TNK option.","Menon et al. Lancet. 2022;400:161-169.",["AcT","Alteplase compared to Tenecteplase"]),
T("TRACE-2","2023","Acute ischemic stroke thrombolysis","Acute ischemic stroke","Tenecteplase 0.25 mg/kg","Thrombolytic choice","Is tenecteplase noninferior to alteplase in AIS?","AIS eligible for IV thrombolysis","Alteplase","1430","mRS 0–1 at 90 days","Tenecteplase was noninferior to alteplase.","Added international support for TNK 0.25 mg/kg.","Bolus thrombolytic may simplify care.","Open-label; population differences.","Generalizability to all systems needs verification.","Strengthened TNK guideline support.","Wang et al. Lancet. 2023;401:645-654.",["TRACE 2"]),
T("EXTEND-IA TNK","2018","Acute ischemic stroke thrombolysis","LVO bridging thrombolysis","Tenecteplase before EVT","Thrombolytic choice","Does tenecteplase improve reperfusion before thrombectomy?","LVO patients planned for EVT","Alteplase","202","Substantial reperfusion before EVT","Tenecteplase improved early reperfusion and functional outcomes signal.","Supported TNK particularly in LVO before EVT.","Higher fibrin specificity and bolus delivery may improve reperfusion.","Moderate sample size.","LVO-selected; not all AIS.","Influenced TNK selection in thrombectomy candidates.","Campbell et al. N Engl J Med. 2018;378:1573-1582.",["EXTEND IA TNK","EXTEND-IA-TNK"]),
T("ATTEST","2015","Acute ischemic stroke thrombolysis","Acute ischemic stroke","Tenecteplase","Thrombolytic choice","Compare tenecteplase and alteplase using imaging outcomes.","AIS within thrombolysis window","Alteplase",verify,"Penumbra salvage/reperfusion imaging","No definitive clinical superiority; helped feasibility evidence.","Early TNK trial informing later larger RCTs.","TNK pharmacology may improve lysis.","Small phase 2 trial.","Not definitive for clinical outcomes.","Contributed to TNK research pathway.","Parsons et al. Lancet Neurol. 2012/ATTEST publication citation to verify.",[]),
T("WAKE-UP","2018","Wake-up / unknown-onset stroke","Unknown-onset AIS","Alteplase selected by DWI-FLAIR mismatch","Extended-window thrombolysis","Can MRI mismatch identify patients for alteplase with unknown onset?","Wake-up/unknown onset stroke with DWI-FLAIR mismatch","Placebo","503","mRS 0–1 at 90 days","Alteplase improved favorable outcome but increased hemorrhage.","Supported MRI-selected thrombolysis in wake-up stroke.","DWI-FLAIR mismatch estimates recent onset and salvageable tissue.","Stopped early; MRI availability.","Selection excludes many patients.","Changed wake-up stroke eligibility in many systems.","Thomalla et al. N Engl J Med. 2018;379:611-622.",["WAKE UP"]),
T("EXTEND","2019","Wake-up / unknown-onset stroke","AIS 4.5–9 h or wake-up","Alteplase selected by perfusion mismatch","Extended-window thrombolysis","Does perfusion imaging select patients for late alteplase?","AIS 4.5–9 h or wake-up with salvageable tissue","Placebo","225","mRS 0–1 at 90 days","Improved excellent outcome; increased sICH.","Supported perfusion-selected late thrombolysis.","Imaging mismatch identifies penumbra.","Stopped early after WAKE-UP; small sample.","Requires automated perfusion and careful selection.","Expanded late-window thrombolysis concept.","Ma et al. N Engl J Med. 2019;380:1795-1803.",[]),
T("EPITHET","2008","Wake-up / unknown-onset stroke","AIS 3–6 h","Alteplase with perfusion imaging","Imaging-selected thrombolysis","Can mismatch predict alteplase benefit 3–6 hours?","AIS 3–6 h with MRI/perfusion evaluation","Placebo","101","Infarct growth","Trend to less infarct growth/reperfusion; not definitive clinical trial.","Helped develop mismatch-selection paradigm.","Penumbra imaging may identify responders.","Small, phase 2.","Not definitive for outcomes.","Foundation for EXTEND-type selection.","Davis et al. Lancet Neurol. 2008;7:299-309.",[]),

T("MR CLEAN","2015","Endovascular thrombectomy / large vessel occlusion","Anterior circulation LVO","Mechanical thrombectomy","EVT within 6 h","Does EVT improve outcome in anterior circulation LVO?","Proximal anterior LVO within 6 hours","Usual care","500","mRS shift at 90 days","EVT substantially improved functional outcomes.","Opened modern thrombectomy era.","Rapid reperfusion improves disability after LVO.","Device and workflow heterogeneity.","Mostly anterior circulation; time window limited.","Made EVT standard of care.","Berkhemer et al. N Engl J Med. 2015;372:11-20.",["MRCLEAN"]),
T("ESCAPE","2015","Endovascular thrombectomy / large vessel occlusion","Anterior circulation LVO","Mechanical thrombectomy","EVT within 12 h","EVT with imaging/workflow selection in LVO.","Small core, good collaterals, proximal occlusion","Usual care","316","mRS 0–2 and mRS shift","EVT improved independence and reduced mortality.","Validated fast workflow and imaging selection.","Collateral/small-core selection enriches benefit.","Selected population.","Stopped early; high-performing centers.","Influenced comprehensive stroke systems.","Goyal et al. N Engl J Med. 2015;372:1019-1030.",[]),
T("EXTEND-IA","2015","Endovascular thrombectomy / large vessel occlusion","Anterior circulation LVO","Solitaire thrombectomy","EVT with perfusion selection","Does EVT improve reperfusion and outcomes in small-core mismatch patients?","LVO with perfusion mismatch","Alteplase alone","70","Reperfusion and early neurologic improvement","EVT improved reperfusion and functional outcome.","Supported perfusion imaging selection for EVT.","Small core and mismatch predict benefit.","Small trial stopped early.","Highly selected.","Helped establish imaging-selected EVT.","Campbell et al. N Engl J Med. 2015;372:1009-1018.",["EXTEND IA"]),
T("SWIFT PRIME","2015","Endovascular thrombectomy / large vessel occlusion","Anterior circulation LVO","Solitaire thrombectomy","EVT within 6 h","Does stent-retriever EVT improve outcome?","LVO, small-to-moderate core","Medical therapy","196","mRS shift/independence","EVT improved functional independence.","Confirmed stent-retriever benefit.","Fast reperfusion improves outcomes.","Selected imaging criteria.","Stopped early.","Reinforced EVT standard.","Saver et al. N Engl J Med. 2015;372:2285-2295.",["SWIFTPRIME"]),
T("REVASCAT","2015","Endovascular thrombectomy / large vessel occlusion","Anterior circulation LVO","Solitaire thrombectomy","EVT up to 8 h","EVT benefit up to 8 hours?","Anterior LVO, limited core","Medical therapy","206","mRS shift at 90 days","EVT improved disability outcomes.","Extended evidence beyond 6 hours in selected patients.","Persistent occlusion causes disability unless reperfused.","Stopped early; selected population.","Workflow and imaging requirements.","Contributed to EVT standard.","Jovin et al. N Engl J Med. 2015;372:2296-2306.",[]),
T("THRACE","2016","Endovascular thrombectomy / large vessel occlusion","LVO stroke","Mechanical thrombectomy","EVT","EVT plus IVT vs IVT alone?","AIS with proximal occlusion","IV thrombolysis alone",verify,"Functional independence","EVT improved functional outcomes in selected patients.","Added European RCT evidence for EVT.","Endovascular reperfusion improves outcome.","Device/time heterogeneity.","Earlier generation workflow.","Supported EVT adoption.","Bracard et al. Lancet Neurol. 2016;15:1138-1147.",[]),
T("PISTE","2017","Endovascular thrombectomy / large vessel occlusion","LVO stroke","Mechanical thrombectomy","EVT","Pragmatic EVT trial in UK systems.","Anterior circulation LVO","Best medical therapy",verify,"Functional outcome","Stopped early; direction favored EVT.","Supported EVT in health-system implementation.","Reperfusion improves outcome.","Underpowered due to early stop.","Small sample.","Added pragmatic evidence.","Muir et al. J Neurol Neurosurg Psychiatry. 2017;88:38-44.",[]),
T("HERMES collaboration","2016","Endovascular thrombectomy / large vessel occlusion","LVO stroke","Mechanical thrombectomy meta-analysis","EVT evidence synthesis","Pooled patient-level evidence for EVT benefit.","Individual patient data from major EVT RCTs","Medical therapy","1287","mRS shift","EVT improved disability across key subgroups.","Provided definitive pooled estimate and subgroup insights.","Pooling improves precision.","Based on selected RCT populations.","Mostly anterior circulation; early-window data.","Anchored guideline recommendations.","Goyal et al. Lancet. 2016;387:1723-1731.",["HERMES"]),
T("DAWN","2018","Endovascular thrombectomy / large vessel occlusion","Late-window LVO","Mechanical thrombectomy","EVT 6–24 h","Can clinical-core mismatch select late-window EVT patients?","ICA/M1 LVO 6–24 h with mismatch","Medical therapy","206","Utility-weighted mRS and independence","EVT markedly improved independence.","Expanded EVT to 24 hours in selected patients.","Mismatch identifies slow progressors.","Highly selected; stopped early.","Requires advanced imaging/software.","Changed late-window stroke pathways.","Nogueira et al. N Engl J Med. 2018;378:11-21.",[]),
T("DEFUSE 3","2018","Endovascular thrombectomy / large vessel occlusion","Late-window LVO","Mechanical thrombectomy","EVT 6–16 h","Does perfusion mismatch identify late-window EVT benefit?","ICA/M1 LVO 6–16 h with target mismatch","Medical therapy","182","mRS shift","EVT improved functional outcome and independence.","Expanded EVT to 16 hours using perfusion selection.","Target mismatch captures salvageable tissue.","Selected patients; stopped early.","Perfusion access limitations.","Changed guidelines for late-window EVT.","Albers et al. N Engl J Med. 2018;378:708-718.",["DEFUSE-3"]),

T("RESCUE-Japan LIMIT","2022","Large core thrombectomy","Large-core anterior LVO","Mechanical thrombectomy","EVT large core","Does EVT help ASPECTS 3–5 large-core stroke?","ICA/M1 LVO ASPECTS 3–5","Medical care","203","mRS 0–3 at 90 days","EVT improved functional outcome but increased hemorrhage.","First major RCT supporting EVT in selected large cores.","Even large-core patients may have meaningful salvage.","Japan population; imaging criteria.","Generalizability and disability tradeoffs.","Started expansion of EVT beyond ASPECTS ≥6.","Yoshimura et al. N Engl J Med. 2022;386:1303-1313.",["RESCUE Japan LIMIT"]),
T("SELECT2","2023","Large core thrombectomy","Large-core anterior LVO","Mechanical thrombectomy","EVT large core","Does EVT improve outcomes in large ischemic core?","ICA/M1 LVO with ASPECTS 3–5 or core ≥50 mL","Medical care","352","mRS shift","EVT improved functional outcomes.","Strong evidence for large-core EVT.","Reperfusion can reduce severe disability even with large core.","Higher hemorrhage/edema concerns.","Selection and center expertise matter.","Expanded EVT eligibility for large cores.","Sarraj et al. N Engl J Med. 2023;388:1259-1271.",[]),
T("ANGEL-ASPECT","2023","Large core thrombectomy","Large-core anterior LVO","Mechanical thrombectomy","EVT large core","Does EVT benefit large infarct core in Chinese population?","Anterior LVO with ASPECTS 3–5 or large core","Medical care","456","mRS shift","EVT improved 90-day outcomes; more hemorrhage.","Confirmed large-core EVT benefit.","Large core is not always futile.","Population/system differences.","Disability outcome tradeoffs.","Supported guideline expansion.","Huo et al. N Engl J Med. 2023;388:1272-1283.",["ANGEL ASPECT"]),
T("TENSION","2023","Large core thrombectomy","Large-core LVO","Mechanical thrombectomy","EVT large core","Does EVT help extended large infarct defined by ASPECTS 3–5?","Anterior LVO ASPECTS 3–5 up to extended windows","Medical care",verify,"mRS shift","EVT improved outcomes and reduced mortality in reports; verify exact result.","Added European large-core evidence.","ASPECTS-based selection may be practical.","Need verify exact publication data.","Evolving evidence base.","Strengthened large-core recommendations.","TENSION trial citation to verify.",[]),
T("TESLA","2024","Large core thrombectomy","Large-core LVO","Mechanical thrombectomy","EVT large core","Trial of EVT in very large infarct core.","Large-core anterior LVO","Medical care",verify,"Functional outcome","Result to verify from final publication/presentation.","Important for ASPECTS 2–5/large core uncertainty.","Tests limits of benefit.","Evolving data.","Use original source before citing.","May refine very-large-core selection.","TESLA trial citation to verify.",[]),
T("LASTE","2024","Large core thrombectomy","Large-core LVO","Mechanical thrombectomy","EVT large core","EVT in large-core anterior circulation stroke.","Large-core LVO","Medical care",verify,"mRS shift","Result to verify.","Adds evidence in severe large-core stroke.","Reperfusion may help selected severe strokes.","Evolving publication status.","Verify trial details.","May influence ASPECTS 0–5 recommendations.","LASTE trial citation to verify.",[]),
T("MAGNA meta-analysis","2024","Large core thrombectomy","Large-core LVO","EVT meta-analysis","EVT large core","Pooled large-core EVT trial evidence.","Large-core EVT RCTs","Medical care",verify,"mRS shift and safety","Generally supports benefit of EVT in large-core patients; verify exact estimates.","Evidence synthesis for guideline committees.","Pooling increases precision.","Depends on included trials and definitions.","Heterogeneity of imaging/core definitions.","Supports broad but selected large-core EVT.","MAGNA meta-analysis citation to verify.",["MAGNA"]),

T("CHANCE","2013","Minor stroke / TIA / dual antiplatelet therapy","Minor stroke/high-risk TIA","Aspirin + clopidogrel","Early DAPT","Does short-course DAPT reduce early recurrent stroke?","Minor stroke or high-risk TIA within 24 h in China","Aspirin","5170","Stroke at 90 days","DAPT reduced recurrent stroke without significant hemorrhage increase.","Established early short-course DAPT.","Early recurrence risk is platelet-driven.","Chinese population; CYP2C19 issues.","Generalizability debated.","Changed minor stroke/TIA prevention.","Wang et al. N Engl J Med. 2013;369:11-19.",[]),
T("POINT","2018","Minor stroke / TIA / dual antiplatelet therapy","Minor stroke/high-risk TIA","Aspirin + clopidogrel","Early DAPT","Does DAPT reduce ischemic events internationally?","Minor stroke or high-risk TIA within 12 h","Aspirin","4881","Major ischemic events and major hemorrhage","Reduced ischemic events but increased major bleeding.","Confirmed DAPT benefit with bleeding tradeoff; favored limited duration.","Early recurrence prevention.","Bleeding risk with 90 days therapy.","Optimal duration shorter than trial duration.","Guidelines commonly recommend 21–30 days in selected patients.","Johnston et al. N Engl J Med. 2018;379:215-225.",[]),
T("THALES","2020","Minor stroke / TIA / dual antiplatelet therapy","Minor-moderate stroke/high-risk TIA","Aspirin + ticagrelor","Early DAPT","Does ticagrelor plus aspirin reduce stroke/death?","NIHSS ≤5 stroke or high-risk TIA","Aspirin","11016","Stroke or death at 30 days","Reduced stroke/death but increased severe bleeding.","Alternative DAPT option in selected patients.","More potent platelet inhibition may reduce recurrence.","Bleeding risk; modest absolute benefit.","Not for all minor strokes.","Influenced ticagrelor-based DAPT recommendations.","Johnston et al. N Engl J Med. 2020;383:207-217.",[]),
T("SOCRATES","2016","Minor stroke / TIA / dual antiplatelet therapy","Minor stroke/TIA","Ticagrelor monotherapy","Antiplatelet","Ticagrelor vs aspirin after minor stroke/TIA.","Minor stroke/TIA","Aspirin","13199","Stroke/MI/death at 90 days","Ticagrelor not statistically superior overall.","Did not replace aspirin monotherapy broadly.","More potent P2Y12 inhibition may help subgroups.","Overall neutral.","Subgroup findings hypothesis-generating.","Set stage for THALES.","Johnston et al. N Engl J Med. 2016;375:35-43.",[]),
T("MATCH","2004","Minor stroke / TIA / dual antiplatelet therapy","Recent stroke/TIA","Aspirin + clopidogrel long-term","Secondary prevention antiplatelet","Long-term DAPT vs clopidogrel alone?","High-risk recent stroke/TIA","Clopidogrel","7599","Vascular events","No major added benefit; life-threatening bleeding increased.","Long-term DAPT generally avoided.","More antiplatelet effect may prevent events but increases bleeding.","Long-term bleeding outweighed benefit.","High-risk selected population.","Supports short, not chronic, DAPT.","Diener et al. Lancet. 2004;364:331-337.",[]),
T("CHARISMA","2006","Minor stroke / TIA / dual antiplatelet therapy","Atherothrombosis risk","Aspirin + clopidogrel","Secondary prevention antiplatelet","Long-term DAPT in stable vascular disease/risk factors?","Vascular disease or risk factors","Aspirin","15603","MI/stroke/CV death","No significant overall benefit; bleeding increased.","Did not support routine chronic DAPT.","Atherothrombosis platelet activation.","Broad population diluted effects.","Not stroke-specific enough.","Reinforced caution with long-term DAPT.","Bhatt et al. N Engl J Med. 2006;354:1706-1717.",[]),
T("SPS3","2012","Minor stroke / TIA / dual antiplatelet therapy","Lacunar stroke","Aspirin + clopidogrel","Lacunar secondary prevention","Does DAPT prevent recurrence after lacunar stroke?","MRI-proven lacunar infarcts","Aspirin","3020","Recurrent stroke","No reduction; increased bleeding and death signal.","Avoid chronic DAPT after lacunar stroke.","Small vessel disease may not be platelet-combination responsive.","Stopped early for harm/futility.","Specific lacunar population.","Guided lacunar stroke prevention.","SPS3 Investigators. N Engl J Med. 2012;367:817-825.",[]),
T("CAPRIE","1996","Minor stroke / TIA / dual antiplatelet therapy","Atherosclerotic vascular disease","Clopidogrel","Secondary prevention antiplatelet","Clopidogrel vs aspirin in vascular disease.","Recent stroke, MI, or PAD","Aspirin","19185","Ischemic stroke/MI/vascular death","Clopidogrel modestly reduced composite vascular events.","Supported clopidogrel as antiplatelet option.","ADP blockade differs from aspirin.","Modest absolute benefit; mixed vascular population.","Stroke subgroup interpretation limited.","Expanded antiplatelet choices.","CAPRIE Steering Committee. Lancet. 1996;348:1329-1339.",[]),
T("ESPRIT","2006","Minor stroke / TIA / dual antiplatelet therapy","TIA/minor stroke","Aspirin + dipyridamole","Secondary prevention antiplatelet","Aspirin-dipyridamole vs aspirin alone?","TIA/minor ischemic stroke","Aspirin",verify,"Vascular events","Combination reduced vascular events with tolerability issues.","Supported aspirin-dipyridamole option.","Dual pathway antiplatelet effect.","Open-label; headaches/discontinuation.","Less used in modern practice.","Influenced secondary prevention guidelines.","ESPRIT Study Group. Lancet. 2006;367:1665-1673.",[]),
T("ESPS-2","1996","Minor stroke / TIA / dual antiplatelet therapy","Prior stroke/TIA","Aspirin + dipyridamole","Secondary prevention antiplatelet","Dipyridamole/aspirin for recurrent stroke prevention?","Prior stroke/TIA","Placebo/monotherapies",verify,"Stroke recurrence","Combination reduced stroke more than either alone.","Established aspirin-dipyridamole efficacy.","Complementary antiplatelet mechanisms.","Tolerability; older trial.","Background therapy changed.","Added antiplatelet option.","Diener et al. J Neurol Sci. 1996;143:1-13.",["ESPS 2"]),
T("PRoFESS","2008","Minor stroke / TIA / dual antiplatelet therapy","Recent ischemic stroke","Aspirin-dipyridamole vs clopidogrel","Secondary prevention antiplatelet","Which antiplatelet strategy is better after stroke?","Recent ischemic stroke","Clopidogrel","20332","Recurrent stroke","Similar recurrent stroke; more hemorrhage/headache with aspirin-dipyridamole.","Clopidogrel and aspirin-dipyridamole both acceptable.","Compare effective antiplatelets head-to-head.","Noninferiority nuance.","Adherence/tolerability issues.","Informed antiplatelet selection.","Sacco et al. N Engl J Med. 2008;359:1238-1251.",["PROFESS"]),

T("NAVIGATE ESUS","2018","ESUS","Embolic stroke of undetermined source","Rivaroxaban","ESUS antithrombotic","Does rivaroxaban beat aspirin after ESUS?","Recent ESUS","Aspirin","7213","Recurrent stroke/systemic embolism","No reduction in recurrent stroke; bleeding increased.","DOAC not routine for unselected ESUS.","Occult embolism may include anticoagulant-responsive sources.","Trial stopped early; heterogeneous ESUS mechanisms.","Unselected ESUS may be too broad.","Changed ESUS practice away from empiric anticoagulation.","Hart et al. N Engl J Med. 2018;378:2191-2201.",["NAVIGATE-ESUS"]),
T("RE-SPECT ESUS","2019","ESUS","Embolic stroke of undetermined source","Dabigatran","ESUS antithrombotic","Does dabigatran beat aspirin after ESUS?","Recent ESUS","Aspirin","5390","Recurrent stroke","Dabigatran not superior to aspirin overall.","Reinforced no routine DOAC for all ESUS.","Some ESUS may be covert AF/atrial cardiopathy.","Subgroups hypothesis-generating.","Broad ESUS definition.","Supports targeted rather than empiric anticoagulation.","Diener et al. N Engl J Med. 2019;380:1906-1917.",["RESPECT ESUS","RE SPECT ESUS"]),
T("ARCADIA","2024","ESUS","Cryptogenic stroke with atrial cardiopathy","Apixaban","ESUS/atrial cardiopathy","Does apixaban beat aspirin in atrial cardiopathy without AF?","Cryptogenic stroke with atrial cardiopathy","Aspirin","1015","Recurrent stroke","Stopped for futility; apixaban did not reduce recurrence.","Atrial cardiopathy alone did not justify empiric anticoagulation in this trial.","Tests atrial substrate hypothesis.","Specific biomarkers; event rate issues.","Does not exclude other selected groups.","Refined ESUS/atrial cardiopathy strategy.","Kamel et al. JAMA. 2024; citation details to verify.",[]),
T("ATTICUS","2023","ESUS","ESUS with cardioembolic risk factors","Apixaban","ESUS antithrombotic","Apixaban vs monitoring-guided aspirin strategy?","ESUS with risk factors","Aspirin/monitoring strategy",verify,"New ischemic lesions/recurrent events","Result to verify; important but not broadly practice-changing as of current evidence.","Examined enriched ESUS population.","Select higher-risk embolic patients.","Verify exact final publication.","May be underpowered/complex endpoint.","Useful for ESUS nuance.","ATTICUS trial citation to verify.",[]),
T("WARSS","2001","ESUS","Noncardioembolic ischemic stroke","Warfarin","Anticoagulation vs antiplatelet","Warfarin vs aspirin after noncardioembolic stroke.","Recent noncardioembolic stroke","Aspirin","2206","Recurrent ischemic stroke or death","No significant advantage of warfarin over aspirin.","Antiplatelet favored for noncardioembolic stroke.","Anticoagulation could target embolic mechanisms.","Older era; broad population.","Not ESUS by modern criteria.","Precursor to ESUS anticoagulation trials.","Mohr et al. N Engl J Med. 2001;345:1444-1451.",[]),

T("BAATAF","1990","Atrial fibrillation / anticoagulation","Nonvalvular atrial fibrillation","Warfarin","AF stroke prevention","Does warfarin prevent stroke in AF?","Nonrheumatic AF","No warfarin/control",verify,"Stroke/systemic embolism","Warfarin markedly reduced stroke.","Established anticoagulation for AF.","AF-related thromboembolism is anticoagulant-responsive.","Older trial, INR management differs.","Pre-DOAC era.","Foundation for AF anticoagulation.","BAATAF Investigators. N Engl J Med. 1990;323:1505-1511.",[]),
T("SPAF","1991","Atrial fibrillation / anticoagulation","Atrial fibrillation","Warfarin/aspirin","AF stroke prevention","Warfarin and aspirin for AF stroke prevention.","Nonvalvular AF","Placebo/control",verify,"Stroke/systemic embolism","Warfarin effective; aspirin less effective.","Supported risk-based anticoagulation.","Cardioembolic stroke prevention.","Multiple SPAF phases; verify exact trial.","Pre-DOAC era.","Guided AF risk prevention.","SPAF Investigators. Circulation/NEJM citations to verify.",[]),
T("ACTIVE-W","2006","Atrial fibrillation / anticoagulation","Atrial fibrillation","Oral anticoagulation","AF stroke prevention","OAC vs clopidogrel plus aspirin in AF.","AF with stroke risk factors","Clopidogrel + aspirin","6706","Vascular events","OAC superior; trial stopped early.","Anticoagulation preferred over DAPT in AF.","Thrombin-mediated embolism better prevented by anticoagulation.","Warfarin management quality matters.","Pre-DOAC.","Discouraged DAPT as substitute for anticoagulation.","ACTIVE Writing Group. Lancet. 2006;367:1903-1912.",["ACTIVE W"]),
T("ACTIVE-A","2009","Atrial fibrillation / anticoagulation","Atrial fibrillation unsuitable for warfarin","Clopidogrel + aspirin","AF antiplatelet alternative","DAPT vs aspirin when VKA unsuitable.","AF unsuitable for VKA","Aspirin","7554","Major vascular events","Reduced stroke but increased major bleeding.","DAPT inferior conceptually to anticoagulation but option when OAC impossible.","Platelet therapy partly reduces embolic events.","Bleeding tradeoff; not OAC comparison.","Pre-DOAC era.","Limited role after DOACs.","Connolly et al. N Engl J Med. 2009;360:2066-2078.",["ACTIVE A"]),
T("RE-LY","2009","Atrial fibrillation / anticoagulation","Atrial fibrillation","Dabigatran","DOAC AF prevention","Dabigatran vs warfarin in AF.","AF at risk of stroke","Warfarin","18113","Stroke/systemic embolism","Dabigatran 150 mg reduced stroke/embolism; less ICH.","Launched DOAC era.","Direct thrombin inhibition avoids INR variability.","Open-label warfarin arm.","Renal dosing/adherence important.","Changed AF stroke prevention.","Connolly et al. N Engl J Med. 2009;361:1139-1151.",["RELY"]),
T("ROCKET-AF","2011","Atrial fibrillation / anticoagulation","Atrial fibrillation","Rivaroxaban","DOAC AF prevention","Rivaroxaban vs warfarin in AF.","Higher-risk nonvalvular AF","Warfarin","14264","Stroke/systemic embolism","Rivaroxaban noninferior; less ICH, more GI bleeding signal.","Added once-daily DOAC option.","Factor Xa inhibition prevents embolism.","High-risk cohort; warfarin TTR issues.","Bleeding profile nuances.","Expanded DOAC use.","Patel et al. N Engl J Med. 2011;365:883-891.",["ROCKET AF"]),
T("ARISTOTLE","2011","Atrial fibrillation / anticoagulation","Atrial fibrillation","Apixaban","DOAC AF prevention","Apixaban vs warfarin in AF.","Nonvalvular AF with risk factors","Warfarin","18201","Stroke/systemic embolism","Apixaban superior for stroke/embolism, less bleeding and mortality.","Major evidence for apixaban in AF.","Xa inhibition with favorable safety.","Trial population; adherence required.","Renal/dose considerations.","Commonly preferred DOAC option.","Granger et al. N Engl J Med. 2011;365:981-992.",[]),
T("ENGAGE AF-TIMI 48","2013","Atrial fibrillation / anticoagulation","Atrial fibrillation","Edoxaban","DOAC AF prevention","Edoxaban vs warfarin in AF.","AF with moderate/high risk","Warfarin","21105","Stroke/systemic embolism","Edoxaban noninferior; less bleeding.","Supported edoxaban as DOAC option.","Xa inhibition.","Dose and renal function issues.","Less common in some markets.","Expanded DOAC class evidence.","Giugliano et al. N Engl J Med. 2013;369:2093-2104.",["ENGAGE AF"]),
T("AVERROES","2011","Atrial fibrillation / anticoagulation","AF unsuitable for warfarin","Apixaban","AF stroke prevention","Apixaban vs aspirin in warfarin-unsuitable AF.","AF unsuitable for VKA","Aspirin","5599","Stroke/systemic embolism","Apixaban reduced stroke/embolism without large major bleeding increase.","Showed anticoagulation better than aspirin even when VKA unsuitable.","DOAC safety may permit anticoagulation.","Stopped early.","Prevalence of true contraindications varies.","Moved practice away from aspirin for AF.","Connolly et al. N Engl J Med. 2011;364:806-817.",[]),
T("ELAN","2023","Atrial fibrillation / anticoagulation","AIS with AF","Early vs later DOAC","Timing anticoagulation after stroke","When start DOAC after AF-related ischemic stroke?","Recent AIS with AF","Later DOAC start","2013","Composite ischemic/bleeding outcome","Early DOAC was not associated with excess symptomatic ICH and had similar/better composite outcomes.","Supported earlier DOAC initiation in selected patients.","Balances recurrence vs hemorrhagic transformation.","Open-label; selected imaging severity.","Not for all hemorrhagic transformation scenarios.","Changed timing discussions after AF stroke.","Fischer et al. N Engl J Med. 2023;388:2411-2421.",[]),
T("TIMING","2022","Atrial fibrillation / anticoagulation","AIS with AF","Early vs delayed DOAC","Timing anticoagulation after stroke","Early vs delayed NOAC after AIS with AF.","Recent AIS with AF","Delayed NOAC","888","Recurrent stroke/sICH/death","Early start was noninferior; no sICH observed in trial.","Supported safety of early DOAC in selected patients.","Prevent early recurrence without causing ICH.","Registry-based PROBE design.","Excludes highest-risk cases.","Informs practical DOAC timing.","Oldgren et al. Circulation. 2022;146:1056-1066.",[]),
T("RAF","2015","Atrial fibrillation / anticoagulation","AIS with AF","Anticoagulation timing observational","Timing anticoagulation after stroke","Optimal timing of anticoagulation after AF-related stroke.","AIS with AF","Different start times",verify,"Recurrent ischemia/bleeding","Suggested intermediate timing may balance risks.","Generated timing rules before RCTs.","Early recurrence and HT risks compete.","Observational confounding.","Pre-DOAC/mixed therapy.","Informed historical 4-14 day practice.","Paciaroni et al. Stroke. 2015;46:2175-2182.",[]),
T("RAF-NOAC","2017","Atrial fibrillation / anticoagulation","AIS with AF","NOAC timing observational","Timing anticoagulation after stroke","NOAC timing after AF-related AIS.","AIS with AF treated with NOAC","Different start times",verify,"Recurrent events/bleeding","Observed low event rates; timing signals hypothesis-generating.","Added real-world DOAC timing data.","DOACs may be safer earlier than VKA.","Observational.","Selection bias.","Preceded ELAN/TIMING.","Paciaroni et al. J Am Heart Assoc. 2017; citation to verify.",["RAF NOAC"]),

T("NASCET","1991","Carotid stenosis / carotid revascularization","Symptomatic carotid stenosis","Carotid endarterectomy","Carotid disease","Does CEA reduce stroke in symptomatic carotid stenosis?","Recent TIA/stroke with symptomatic carotid stenosis","Medical therapy","verify exact number","Ipsilateral stroke","CEA greatly reduced ipsilateral stroke in severe stenosis.","Established CEA for symptomatic severe carotid stenosis.","Removing culprit plaque prevents recurrent embolism/hypoperfusion.","Surgical risk and stenosis measurement matter.","Older medical therapy; operator dependence.","Core basis for symptomatic carotid revascularization.","NASCET Collaborators. N Engl J Med. 1991;325:445-453.",[]),
T("ECST","1991","Carotid stenosis / carotid revascularization","Symptomatic carotid stenosis","Carotid endarterectomy","Carotid disease","CEA vs medical therapy in symptomatic carotid stenosis.","Recent carotid-territory symptoms","Medical therapy",verify,"Major stroke/death","Benefit strongest in severe stenosis.","Confirmed symptomatic severe stenosis benefit.","Culprit plaque removal.","Different stenosis measurement vs NASCET.","Older medical therapy.","Informs carotid guideline thresholds.","European Carotid Surgery Trialists. Lancet. 1991;337:1235-1243.",[]),
T("ACAS","1995","Carotid stenosis / carotid revascularization","Asymptomatic carotid stenosis","Carotid endarterectomy","Carotid disease","Does CEA help asymptomatic carotid stenosis?","Asymptomatic ≥60% stenosis","Medical therapy","1662","Ipsilateral stroke/perioperative events","CEA reduced long-term ipsilateral stroke with low perioperative risk.","Supported selected asymptomatic CEA in low-risk patients.","Prevent future plaque-related stroke.","Benefit small and depends on surgical risk.","Modern medical therapy may reduce benefit.","Historical basis for asymptomatic CEA.","ACAS Executive Committee. JAMA. 1995;273:1421-1428.",[]),
T("ACST-1","2004/2010","Carotid stenosis / carotid revascularization","Asymptomatic carotid stenosis","Carotid endarterectomy","Carotid disease","Immediate vs deferred CEA for asymptomatic stenosis.","Asymptomatic substantial carotid stenosis","Deferred surgery/medical therapy","3120","Stroke/death","CEA reduced long-term stroke risk in selected patients.","Supported selected asymptomatic CEA but benefit accrues over years.","Preventive revascularization.","Modern medical therapy issue.","Requires long life expectancy and low periop risk.","Influenced asymptomatic carotid management.","Halliday et al. Lancet. 2004;363:1491-1502; 10-year results Lancet. 2010.",["ACST 1"]),
T("ACST-2","2021","Carotid stenosis / carotid revascularization","Asymptomatic carotid stenosis","CEA vs CAS","Carotid disease","CEA vs carotid stenting in asymptomatic severe stenosis.","Asymptomatic severe stenosis selected for procedure","CEA or CAS","3625","Periprocedural and long-term stroke/death","CEA and CAS had similar long-term disabling/fatal stroke outcomes in experienced hands.","Compared procedure types, not procedure vs modern medical therapy.","Both revascularize carotid plaque.","No medical-only arm.","Operator expertise selection.","Informs choice between CEA and CAS.","Halliday et al. Lancet. 2021;398:1065-1073.",["ACST 2"]),
T("CREST","2010","Carotid stenosis / carotid revascularization","Symptomatic/asymptomatic carotid stenosis","CEA vs CAS","Carotid disease","CAS vs CEA for carotid stenosis.","Symptomatic and asymptomatic carotid stenosis","CEA or CAS","2502","Stroke/MI/death and ipsilateral stroke","Similar composite; more stroke with CAS, more MI with CEA; age interaction.","Established nuanced CEA vs CAS selection.","Both restore lumen but risks differ.","Composite endpoint includes MI and stroke with different patient impact.","Operator credentialing; mixed symptomatic status.","Guided age/anatomy/risk-based choice.","Brott et al. N Engl J Med. 2010;363:11-23.",[]),
T("CREST-2","ongoing","Carotid stenosis / carotid revascularization","Asymptomatic carotid stenosis","CEA or CAS plus intensive medical therapy","Carotid disease","Does revascularization add benefit over intensive medical therapy?","High-grade asymptomatic carotid stenosis","Intensive medical therapy alone",verify,"Stroke/death","Ongoing/verify current results.","Will define modern asymptomatic carotid management.","Modern medical therapy may lower baseline stroke risk.","No final practice-changing result until published.","Enrollment/design considerations.","Important pending evidence.","CREST-2 trial citation to verify.",["CREST 2"]),
T("EVA-3S","2006","Carotid stenosis / carotid revascularization","Symptomatic carotid stenosis","CAS vs CEA","Carotid disease","CAS vs CEA in symptomatic stenosis.","Recently symptomatic severe stenosis","CEA","527","30-day stroke/death","CAS had higher early stroke/death; trial stopped early.","Raised safety concerns for CAS in symptomatic patients.","Less invasive stenting may avoid surgical risks but embolic risk matters.","Operator experience/device era.","Early stopped trial.","Favored CEA for many symptomatic patients.","Mas et al. N Engl J Med. 2006;355:1660-1671.",["EVA 3S"]),
T("SPACE","2006","Carotid stenosis / carotid revascularization","Symptomatic carotid stenosis","CAS vs CEA","Carotid disease","Stenting vs endarterectomy in symptomatic stenosis.","Symptomatic severe carotid stenosis","CEA","1200","Ipsilateral stroke/death","Failed to prove noninferiority of CAS.","Added uncertainty/caution for CAS.","Compare less invasive vs surgery.","Noninferiority margin and event rates debated.","Device/operator variation.","Guided careful CAS selection.","SPACE Collaborative Group. Lancet. 2006;368:1239-1247.",[]),
T("ICSS","2010","Carotid stenosis / carotid revascularization","Symptomatic carotid stenosis","CAS vs CEA","Carotid disease","International comparison of CAS vs CEA.","Symptomatic carotid stenosis","CEA","1713","Stroke/death/MI","CAS had higher early stroke risk; long-term outcomes more similar.","Supported CEA as default in many symptomatic patients.","Periprocedural embolic risk differs.","MRI substudy showed more silent infarcts with CAS.","Operator/device era effects.","Influenced symptomatic carotid procedure choice.","ICSS Investigators. Lancet. 2010;375:985-997.",[]),
T("SAPPHIRE","2004","Carotid stenosis / carotid revascularization","High surgical risk carotid stenosis","CAS with protection vs CEA","Carotid disease","CAS vs CEA in high-surgical-risk patients.","High-risk symptomatic/asymptomatic stenosis","CEA","334","Death/stroke/MI","CAS noninferior/superior composite in high-risk cohort.","Supported CAS option in high surgical risk.","Avoids surgical complications in high-risk anatomy/comorbidity.","Industry/device era; mixed symptoms.","Generalizability limited.","Led to CAS adoption in selected high-risk patients.","Yadav et al. N Engl J Med. 2004;351:1493-1501.",[]),
T("CAVATAS","2001","Carotid stenosis / carotid revascularization","Carotid stenosis","Endovascular therapy vs CEA","Carotid disease","Early endovascular carotid therapy vs surgery.","Mostly symptomatic carotid stenosis","CEA",verify,"Stroke/death","Similar major outcomes but high restenosis after endovascular therapy.","Early precursor to modern CAS trials.","Less invasive carotid repair hypothesis.","Pre-stent/early technology.","Not reflective of current devices.","Historical trial for CAS evolution.","CAVATAS Investigators. Lancet. 2001;357:1729-1737.",[]),
T("ACT I","2016","Carotid stenosis / carotid revascularization","Asymptomatic carotid stenosis","CAS vs CEA","Carotid disease","CAS vs CEA in standard-risk asymptomatic patients.","Asymptomatic severe stenosis, not high surgical risk","CEA","1453","Death/stroke/MI and ipsilateral stroke","CAS noninferior to CEA in selected patients.","Supports CAS as option in carefully selected asymptomatic patients.","Procedure choice question.","No medical-only arm; selected operators.","Modern medical therapy context unresolved.","Informs procedural selection.","Rosenfield et al. N Engl J Med. 2016;374:1011-1020.",["ACT 1"]),

T("WASID","2005","Intracranial atherosclerosis","Symptomatic intracranial stenosis","Warfarin vs aspirin","Intracranial stenosis","Warfarin or aspirin for intracranial stenosis?","TIA/stroke with 50–99% intracranial stenosis","Aspirin/warfarin","569","Stroke/death","Warfarin had more adverse events and no benefit over aspirin.","Aspirin preferred over warfarin.","Atherosclerotic stenosis may be thrombotic/embolic.","Older medical therapy.","Did not test aggressive modern risk management.","Foundation for ICAD medical therapy.","Chimowitz et al. N Engl J Med. 2005;352:1305-1316.",[]),
T("SAMMPRIS","2011","Intracranial atherosclerosis","Severe symptomatic intracranial stenosis","Stenting plus medical therapy","Intracranial stenosis","Does Wingspan stenting add benefit to aggressive medical therapy?","Recent TIA/stroke with 70–99% intracranial stenosis","Aggressive medical therapy","451","Stroke/death","Stenting increased early stroke/death; aggressive medical therapy superior.","Established aggressive medical therapy as first-line for severe ICAD.","Mechanical stenosis treatment may reduce recurrence but procedural risk high.","High early procedural harm.","Experienced centers but still high risk.","Avoid routine intracranial stenting initially.","Chimowitz et al. N Engl J Med. 2011;365:993-1003.",[]),
T("VISSIT","2015","Intracranial atherosclerosis","Symptomatic intracranial stenosis","Balloon-expandable stent","Intracranial stenosis","Balloon-expandable stent vs medical therapy.","Symptomatic intracranial stenosis","Medical therapy","112","Stroke/TIA/death","Stenting worse than medical therapy.","Confirmed harm/lack of benefit of intracranial stenting approach.","Treat fixed stenosis hypothesis.","Stopped early; device-specific.","Small trial but consistent with SAMMPRIS.","Reinforced medical-first ICAD care.","Zaidat et al. JAMA. 2015;313:1240-1248.",[]),
T("CASSISS","2022","Intracranial atherosclerosis","Severe symptomatic intracranial stenosis","Stenting plus medical therapy","Intracranial stenosis","Can refined selection make stenting beneficial?","Severe symptomatic intracranial stenosis beyond acute phase","Medical therapy","380","Stroke/death","No significant benefit from adding stenting.","Even improved selection did not prove routine stenting benefit.","Lower procedural risk might reveal benefit.","Event rates lower than expected.","Highly selected centers/patients.","Continued medical-first strategy.","Gao et al. JAMA. 2022;328:534-542.",[]),

T("INTERACT","2008","Intracerebral hemorrhage","Acute ICH","Intensive BP lowering","ICH BP management","Feasibility/safety of early intensive BP lowering.","Acute spontaneous ICH","Guideline BP management",verify,"Hematoma growth/safety","Suggested intensive BP lowering safe and may reduce hematoma growth.","Set stage for INTERACT2.","BP may drive hematoma expansion.","Pilot/phase 2.","Not definitive clinical outcome.","Informed ICH BP trials.","Anderson et al. Lancet Neurol. 2008;7:391-399.",[]),
T("INTERACT2","2013","Intracerebral hemorrhage","Acute ICH","Intensive BP lowering","ICH BP management","Does SBP <140 improve outcome after ICH?","ICH within 6 h with elevated SBP","SBP <180","2839","Death or major disability","Primary dichotomy borderline; ordinal mRS improved; safe.","Supported early SBP lowering to about 140 in many ICH patients.","Reduce hematoma expansion.","Modest effect; open-label.","Not ultra-intensive; selected BP range.","Changed ICH BP targets.","Anderson et al. N Engl J Med. 2013;368:2355-2365.",[]),
T("ATACH","2010","Intracerebral hemorrhage","Acute ICH","Nicardipine BP lowering","ICH BP management","Pilot intensive BP reduction after ICH.","Acute ICH with high SBP","Dose tiers",verify,"Safety/tolerability","Showed feasibility/safety, led to ATACH-II.","BP lowering may limit expansion.","Pilot.","Not powered for outcomes.","Prepared definitive trial.","Antihypertensive Treatment of Acute Cerebral Hemorrhage citation to verify.",[]),
T("ATACH-II","2016","Intracerebral hemorrhage","Acute ICH","Very intensive BP lowering","ICH BP management","SBP 110–139 vs 140–179 after ICH?","ICH within 4.5 h, SBP high","Standard BP lowering","1000","Death/disability","No outcome benefit; renal adverse events increased.","Very intensive lowering not superior and may harm.","Test lower SBP target.","Stopped for futility.","Specific severe BP target.","Tempered aggressive BP lowering.","Qureshi et al. N Engl J Med. 2016;375:1033-1043.",["ATACH II"]),
T("FAST","2008","Intracerebral hemorrhage","Acute ICH","Recombinant factor VIIa","Hemostatic therapy","Does rFVIIa improve outcome by limiting expansion?","Spontaneous ICH within 4 h","Placebo","841","Death/severe disability","Reduced hematoma growth but no clinical benefit; arterial events increased.","Hemostatic effect did not translate to routine use.","Expansion is key outcome driver.","Thrombotic risk; outcome neutral.","Selected early ICH.","Did not support routine rFVIIa.","Mayer et al. N Engl J Med. 2008;358:2127-2137.",[]),
T("TICH-2","2018","Intracerebral hemorrhage","Acute ICH","Tranexamic acid","Hemostatic therapy","Does TXA improve outcome in ICH?","Spontaneous ICH within 8 h","Placebo","2325","mRS at 90 days","No significant functional benefit; reduced early deaths/hematoma expansion signals.","TXA not routine for all ICH but informs subgroups.","Antifibrinolysis may limit expansion.","Broad time window; modest expansion effect.","Subgroups under study.","Guided further TXA research.","Sprigg et al. Lancet. 2018;391:2107-2115.",["TICH 2"]),
T("ANNEXA-I","2024","Intracerebral hemorrhage","Factor Xa inhibitor-associated ICH","Andexanet alfa","Anticoagulant reversal","Andexanet vs usual care for FXa-associated ICH.","Acute ICH on factor Xa inhibitors","Usual care","530","Hemostatic efficacy","Improved hemostatic efficacy; thrombotic events concern; verify final details.","Important reversal evidence.","Rapid reversal may limit expansion.","Cost/thrombosis; clinical outcome nuance.","Specific DOAC-associated ICH.","Informs reversal protocols.","ANNEXA-I Investigators. N Engl J Med. 2024; citation to verify.",["ANNEXA I"]),
T("RESTART","2019","Intracerebral hemorrhage","ICH survivors needing antiplatelet","Restart antiplatelet","Antiplatelet after ICH","Is restarting antiplatelet safe after ICH?","Survivors of ICH previously on antithrombotics","Avoid antiplatelet","537","Recurrent ICH","Restarting antiplatelet did not increase recurrent ICH significantly.","Provides reassurance when antiplatelet indicated.","Balance ischemic vs hemorrhagic risk.","Open-label; limited power.","Selected survivors.","Influenced post-ICH antiplatelet decisions.","RESTART Collaboration. Lancet. 2019;393:2613-2623.",[]),
T("STICH","2005","Intracerebral hemorrhage","Supratentorial ICH","Early surgery","ICH surgery","Early surgical evacuation vs conservative care.","Supratentorial ICH","Conservative care","1033","Functional outcome/death","No overall benefit of early surgery.","Routine open surgery not supported broadly.","Remove mass/hematoma toxicity.","Heterogeneous locations; crossover.","May miss superficial subgroup.","Guided selective surgery approach.","Mendelow et al. Lancet. 2005;365:387-397.",[]),
T("STICH II","2013","Intracerebral hemorrhage","Superficial lobar ICH","Early surgery","ICH surgery","Early surgery for superficial lobar ICH without IVH.","Conscious patients with superficial lobar ICH","Initial conservative treatment","601","Unfavorable outcome","No significant primary benefit; possible small survival advantage.","Surgery may help selected superficial lobar cases but not definitive.","Accessible hematoma may be removed safely.","Narrow selected population.","Modest/uncertain effect.","Informs individualized neurosurgical decisions.","Mendelow et al. Lancet. 2013;382:397-408.",["STICH 2"]),
T("MISTIE III","2019","Intracerebral hemorrhage","Moderate-large ICH","Minimally invasive surgery + alteplase","ICH surgery","Does minimally invasive catheter evacuation improve outcome?","Supratentorial ICH ≥30 mL","Medical care","506","mRS 0–3 at 1 year","Primary endpoint neutral; better outcomes when clot reduction achieved in analyses.","Did not establish routine MISTIE, but supports evacuation target concept.","Less invasive removal reduces mass/toxicity.","Technical success variable.","Subgroup/post hoc target findings.","Informed newer surgical trials.","Hanley et al. Lancet. 2019;393:1021-1032.",[]),
T("ENRICH","2023","Intracerebral hemorrhage","Lobar/anterior basal ganglia ICH","Minimally invasive parafascicular surgery","ICH surgery","Early minimally invasive evacuation vs medical management.","Spontaneous ICH, selected locations/volumes","Medical management",verify,"Utility-weighted mRS","Reported benefit driven by lobar subgroup; verify final details.","Important modern surgical ICH evidence.","Early evacuation may improve outcomes in selected ICH.","Selection and location-dependent benefit.","Verify exact subgroup data.","May change selected lobar ICH surgery practice.","ENRICH trial citation to verify.",[]),
T("CLEAR III","2017","Intracerebral hemorrhage","IVH with obstructive hydrocephalus","Intraventricular alteplase","IVH therapy","Does alteplase through EVD improve outcome?","IVH requiring EVD","Saline irrigation","500","mRS ≤3","No significant functional benefit; mortality lower but more survivors with severe disability.","Not routine for functional improvement; selected use debated.","Clearing IVH may reduce hydrocephalus/toxicity.","Outcome neutral; disability tradeoff.","Requires EVD/IVH selection.","Guided IVH thrombolysis discussions.","Hanley et al. Lancet. 2017;389:603-611.",[]),

T("ISAT","2002","Subarachnoid hemorrhage","Ruptured intracranial aneurysm","Endovascular coiling","Aneurysmal SAH","Coiling vs clipping for ruptured aneurysms suitable for both.","Ruptured aneurysm SAH, mostly anterior circulation small aneurysms","Surgical clipping","2143","Death/dependency","Coiling reduced death/dependency at 1 year; higher recurrence/rebleed risk long-term.","Shifted many suitable ruptured aneurysms toward coiling.","Less invasive aneurysm occlusion may reduce early morbidity.","Selected aneurysms; durability concerns.","Not all aneurysm anatomy included.","Changed aneurysmal SAH treatment.","Molyneux et al. Lancet. 2002;360:1267-1274.",[]),
T("BRAT","2012","Subarachnoid hemorrhage","Ruptured aneurysm","Clip-first vs coil-first policy","Aneurysmal SAH","Pragmatic clipping vs coiling policy.","SAH patients at single center","Alternative policy",verify,"mRS/death","Results nuanced by aneurysm location; anterior circulation often favored coiling less clearly over time.","Pragmatic complement to ISAT.","Real-world aneurysm allocation.","Single-center; crossover.","Not pure procedure comparison.","Informs aneurysm-specific decision making.","Spetzler et al. J Neurosurg. 2013; citation to verify.",[]),
T("CONSCIOUS-1","2008","Subarachnoid hemorrhage","Aneurysmal SAH vasospasm","Clazosentan","SAH vasospasm/DCI","Endothelin antagonist for vasospasm prevention.","Aneurysmal SAH","Placebo",verify,"Angiographic vasospasm","Reduced angiographic vasospasm dose-dependently.","Biologic proof but clinical outcomes uncertain.","Endothelin mediates vasospasm.","Phase 2; pulmonary/hypotension issues.","Angiographic surrogate.","Led to CONSCIOUS-2/3.","Macdonald et al. Stroke. 2008; citation to verify.",["CONSCIOUS 1"]),
T("CONSCIOUS-2","2011","Subarachnoid hemorrhage","Aneurysmal SAH clipped aneurysms","Clazosentan","SAH vasospasm/DCI","Does clazosentan improve clinical outcome after clipping?","Clipped aneurysmal SAH","Placebo",verify,"Vasospasm-related morbidity/all-cause mortality","Did not significantly improve primary clinical endpoint; adverse events.","Reduced vasospasm did not clearly improve outcomes.","Vasospasm is not the only DCI mechanism.","Endpoint and adverse effects.","Clipped-only population.","Tempered endothelin antagonist enthusiasm.","Macdonald et al. Lancet Neurol. 2011;10:618-625.",["CONSCIOUS 2"]),
T("CONSCIOUS-3","2012","Subarachnoid hemorrhage","Aneurysmal SAH coiled aneurysms","Clazosentan","SAH vasospasm/DCI","Clazosentan after coiling.","Coiled aneurysmal SAH","Placebo",verify,"Vasospasm-related morbidity/all-cause mortality","Did not improve clinical outcome; adverse effects.","No routine clazosentan in earlier era.","Surrogate-to-outcome gap.","Stopped/negative clinical endpoint.","Coiled-only population.","Guided DCI drug development.","CONSCIOUS-3 citation to verify.",["CONSCIOUS 3"]),
T("NEWTON-2","2024","Subarachnoid hemorrhage","Aneurysmal SAH DCI","Intraventricular nimodipine microparticles","SAH DCI prevention","Does sustained-release nimodipine improve outcome?","Aneurysmal SAH with EVD","Standard nimodipine/placebo",verify,"Functional outcome/DCI","Result to verify.","Important modern SAH DCI trial.","Local nimodipine may reduce systemic hypotension.","Evolving evidence.","Verify final publication.","May affect future DCI prevention.","NEWTON-2 citation to verify.",["NEWTON 2"]),
T("ULTRA","2021","Subarachnoid hemorrhage","Aneurysmal SAH","Ultra-early tranexamic acid","SAH rebleeding prevention","Does ultra-early TXA improve outcome by reducing rebleeding?","Suspected/proven aSAH early after onset","Placebo/usual care",verify,"Functional outcome","Did not improve 6-month outcome despite possible rebleeding reduction.","Short TXA not routine for outcome improvement in all systems.","Prevent early rebleeding before aneurysm secured.","Rapid aneurysm treatment may reduce added value.","System-dependent timing.","Informs antifibrinolytic use.","Post et al. Lancet. 2021; citation to verify.",[]),
T("HIMALAIA","2018","Subarachnoid hemorrhage","SAH delayed cerebral ischemia","Induced hypertension","SAH DCI treatment","Induced hypertension for DCI after SAH.","Aneurysmal SAH with DCI","No induced hypertension",verify,"Functional outcome","Stopped early; no definitive benefit.","Evidence for induced hypertension remains limited.","Augment perfusion during DCI.","Underpowered.","Practice based partly on physiology/observational data.","Highlights evidence gap.","HIMALAIA citation to verify.",[]),
T("MASH-2","2012","Subarachnoid hemorrhage","Aneurysmal SAH","Magnesium sulfate","SAH neuroprotection","Does magnesium improve outcome after SAH?","Aneurysmal SAH","Placebo","1204","Poor outcome","No improved outcome.","Magnesium not routine for aSAH outcome improvement.","Neuroprotection/vasospasm hypothesis.","Neutral despite biologic rationale.","Dose/timing possible issues.","Stopped routine magnesium enthusiasm.","Dorhout Mees et al. Lancet. 2012;380:44-49.",["MASH 2"]),
T("IMASH","2010","Subarachnoid hemorrhage","Aneurysmal SAH","IV magnesium","SAH neuroprotection","Magnesium after aneurysmal SAH.","Aneurysmal SAH","Placebo",verify,"Clinical outcome","No clear benefit; verify exact results.","Contributed to negative magnesium evidence.","Neuroprotection hypothesis.","Underpowered/neutral.","Superseded by MASH-2.","Informs no routine magnesium.","IMASH citation to verify.",[]),
T("STASH","2012","Subarachnoid hemorrhage","Aneurysmal SAH","Simvastatin","SAH neuroprotection/vasospasm","Does simvastatin improve outcome after SAH?","Aneurysmal SAH","Placebo","803","mRS outcome","No benefit.","Statins not routine solely for SAH outcome improvement.","Pleiotropic vascular effects.","Neutral despite smaller studies.","Dose/timing uncertainties.","Changed practice away from routine SAH statins.","Kirkpatrick et al. Lancet Neurol. 2014; citation to verify.",[]),

T("SPARCL","2006","Lipid therapy","Recent stroke/TIA without known CHD","High-dose atorvastatin","Lipid therapy secondary prevention","Does high-dose atorvastatin reduce recurrent stroke?","Recent stroke/TIA, LDL elevated, no known CHD","Placebo","4731","Fatal/nonfatal stroke","Reduced recurrent stroke; small hemorrhagic stroke signal.","Established intensive statin after ischemic stroke/TIA.","LDL lowering reduces atherosclerotic events.","Hemorrhagic stroke signal debated.","Selected non-cardioembolic-ish population.","Core secondary prevention trial.","Amarenco et al. N Engl J Med. 2006;355:549-559.",[]),
T("Treat Stroke to Target","2020","Lipid therapy","Atherosclerotic stroke/TIA","LDL target <70 mg/dL","Lipid target","Lower LDL target vs higher target after stroke/TIA.","Recent ischemic stroke/TIA with atherosclerosis","LDL 90–110 target","2860","Major cardiovascular events","Lower LDL target reduced major vascular events.","Supports LDL <70 mg/dL target in atherosclerotic stroke/TIA.","Aggressive LDL lowering stabilizes plaque.","Open-label target strategy.","Population with atherosclerosis.","Changed lipid target recommendations.","Amarenco et al. N Engl J Med. 2020;382:9.",["TST"]),
T("Heart Protection Study","2002","Lipid therapy","High vascular risk","Simvastatin","Vascular risk reduction","Statin benefit in high-risk patients including cerebrovascular disease.","High-risk vascular patients","Placebo","20536","Major vascular events","Simvastatin reduced major vascular events.","Supported statins across high-risk groups.","LDL lowering benefit independent of baseline cholesterol.","Not stroke-specific exclusively.","Older statin intensity.","Broadened vascular prevention statin use.","Heart Protection Study Collaborative Group. Lancet. 2002;360:7-22.",["HPS"]),
T("FOURIER","2017","Lipid therapy","Atherosclerotic cardiovascular disease","Evolocumab","PCSK9 therapy","Does PCSK9 inhibition reduce vascular events?","ASCVD on statins","Placebo","27564","CV composite","Reduced major CV events including ischemic stroke.","Supports PCSK9 for very high-risk patients needing LDL lowering.","Further LDL lowering reduces events.","Not stroke-only trial.","Cost/access; injection.","Informs add-on lipid therapy.","Sabatine et al. N Engl J Med. 2017;376:1713-1722.",[]),
T("ODYSSEY Outcomes","2018","Lipid therapy","Recent ACS high risk","Alirocumab","PCSK9 therapy","Alirocumab after ACS reduces events?","Recent ACS on intensive statin","Placebo","18924","CV composite","Reduced ischemic events including stroke signal.","Supports PCSK9 use in high-risk vascular patients.","LDL lowering after ACS.","Not stroke-specific.","Population ACS not stroke entry.","Secondary vascular prevention option.","Schwartz et al. N Engl J Med. 2018;379:2097-2107.",[]),

T("PROGRESS","2001","Blood pressure management","Prior stroke/TIA","Perindopril-based BP lowering","Secondary prevention BP","Does BP lowering reduce recurrent stroke?","Prior stroke/TIA","Placebo","6105","Stroke recurrence","Reduced recurrent stroke, especially combination therapy.","Established BP lowering for secondary stroke prevention.","BP reduction lowers vascular risk even without hypertension.","Regimen-specific; older era.","Adherence and BP targets differ.","Core secondary prevention BP trial.","PROGRESS Collaborative Group. Lancet. 2001;358:1033-1041.",[]),
T("SPS3 BP arm","2013","Blood pressure management","Lacunar stroke","Lower SBP target","Secondary prevention BP","Lower vs higher SBP target after lacunar stroke.","Recent lacunar stroke","Higher SBP target","3020","Recurrent stroke","Nonsignificant stroke reduction; significant ICH reduction signal.","Supports intensive BP control especially lacunar/small vessel disease.","Small vessel disease is BP-sensitive.","Power/event rate issues.","Applies to lacunar stroke.","Influenced BP target discussions.","SPS3 Study Group. Lancet. 2013;382:507-515.",["SPS3 BP"]),
T("CATIS","2014","Blood pressure management","Acute ischemic stroke","Immediate BP reduction","AIS BP management","Does early BP lowering improve AIS outcomes?","AIS with elevated BP not receiving thrombolysis","No antihypertensive during hospitalization","4071","Death/major disability","No improvement in death/disability.","Routine early BP lowering in AIS not beneficial absent indication.","Perfusion may depend on BP acutely.","Chinese population; excluded thrombolysis.","Timing/targets matter.","Supports permissive hypertension approach.","He et al. JAMA. 2014;311:479-489.",[]),
T("ENOS","2015","Blood pressure management","Acute stroke","Transdermal glyceryl trinitrate/BP lowering","Acute stroke BP","Does GTN or continuing antihypertensives improve acute stroke outcome?","Acute ischemic or hemorrhagic stroke","No GTN/stop meds","4011","mRS at 90 days","GTN did not improve functional outcome overall.","No routine GTN for acute stroke outcome improvement.","NO donor may lower BP and improve collateral flow.","Mixed stroke types; timing subgroup debated.","Prehospital ultra-early question separate.","Guided acute BP therapy caution.","ENOS Trial Investigators. Lancet. 2015;385:617-628.",[]),

T("CLOSURE I","2012","PFO and cryptogenic stroke","Cryptogenic stroke/TIA with PFO","PFO closure device","PFO closure","Does STARFlex PFO closure reduce recurrence?","Cryptogenic stroke/TIA with PFO","Medical therapy","909","Stroke/TIA/death","No significant benefit; procedural AF/complications.","Early closure trial negative.","Paradoxical embolism mechanism.","Device limitations; included TIA.","Later better devices/selection changed field.","Did not support early broad closure.","Furlan et al. N Engl J Med. 2012;366:991-999.",["CLOSURE 1"]),
T("PC Trial","2013","PFO and cryptogenic stroke","Cryptogenic embolism with PFO","PFO closure","PFO closure","Closure vs medical therapy in PFO-associated events.","Cryptogenic stroke/TIA/peripheral embolism with PFO","Medical therapy","414","Death/stroke/TIA/peripheral embolism","Did not show significant benefit; underpowered.","Contributed to early uncertainty.","Prevent paradoxical embolism.","Small sample/low event rate.","Mixed outcomes.","Set stage for pooled analyses.","Meier et al. N Engl J Med. 2013;368:1083-1091.",["PC"]),
T("RESPECT","2013/2017","PFO and cryptogenic stroke","Cryptogenic stroke with PFO","Amplatzer PFO closure","PFO closure","Closure vs medical therapy after cryptogenic stroke.","Age 18–60 cryptogenic stroke with PFO","Medical therapy","980","Recurrent ischemic stroke","Long-term follow-up showed reduced recurrent stroke with closure.","Supported closure in selected younger patients.","Paradoxical embolism prevention.","Initial analysis neutral; long follow-up needed.","Careful patient selection critical.","Changed PFO closure guidelines.","Saver et al. N Engl J Med. 2017;377:1022-1032.",[]),
T("CLOSE","2017","PFO and cryptogenic stroke","Cryptogenic stroke with high-risk PFO","PFO closure","PFO closure","Closure in PFO with atrial septal aneurysm/large shunt.","Young patients with cryptogenic stroke and high-risk PFO","Antiplatelet therapy","663","Recurrent stroke","No strokes in closure group vs antiplatelet arm over follow-up; AF increased.","Strong evidence for high-risk PFO closure.","High-risk anatomy enriches causal PFO.","Open-label; selected young population.","AF/procedural risks.","Changed closure recommendations.","Mas et al. N Engl J Med. 2017;377:1011-1021.",[]),
T("REDUCE","2017","PFO and cryptogenic stroke","Cryptogenic stroke with PFO","Gore device PFO closure","PFO closure","Closure plus antiplatelet vs antiplatelet alone.","Cryptogenic stroke with PFO","Antiplatelet therapy","664","Recurrent ischemic stroke/new brain infarct","Reduced recurrent stroke but increased AF.","Supported closure in selected patients.","Prevent paradoxical emboli.","Device/procedure AF risk.","Young selected patients.","Guideline support for closure.","Søndergaard et al. N Engl J Med. 2017;377:1033-1042.",[]),
T("DEFENSE-PFO","2018","PFO and cryptogenic stroke","High-risk PFO cryptogenic stroke","PFO closure","PFO closure","Closure in high-risk PFO anatomy.","Cryptogenic stroke with high-risk PFO","Medical therapy","120","Stroke/vascular death/major bleeding","Closure reduced recurrent events in small trial.","Supported high-risk anatomy selection.","Large shunt/ASA/hypermobility may indicate causality.","Small sample.","Wide confidence intervals.","Adds high-risk PFO evidence.","Lee et al. J Am Coll Cardiol. 2018;71:2335-2342.",["DEFENSE PFO"]),

T("RACECAT","2022","Stroke systems of care","Suspected LVO prehospital","Direct to thrombectomy center vs local stroke center","EMS destination","Should suspected LVO bypass local stroke centers?","Prehospital suspected LVO in region with transfer systems","Nearest local stroke center","1401","mRS at 90 days","No overall benefit of direct thrombectomy-center transport.","Destination decisions must be system-specific.","Bypass may speed EVT but delay IVT.","Regional geography and transfer performance key.","May not apply to all systems.","Guides EMS routing nuance.","Pérez de la Ossa et al. JAMA. 2022;327:1782-1794.",[]),
T("DIRECT-MT","2020","Stroke systems of care","LVO eligible for IVT and EVT","Direct EVT vs bridging IVT","Bridging thrombolysis","Is EVT alone noninferior to IVT+EVT?","LVO patients presenting to EVT centers","IVT plus EVT","656","mRS shift","EVT alone met noninferiority in trial, but margin debated.","Did not eliminate bridging IVT globally.","Avoid delays/bleeding from IVT if EVT planned.","Open-label; noninferiority margin; regional workflow.","Generalizability debated.","Triggered multiple direct EVT trials.","Yang et al. N Engl J Med. 2020;382:1981-1993.",["DIRECT MT"]),
T("DEVT","2021","Stroke systems of care","LVO bridging-eligible","Direct EVT","Bridging thrombolysis","EVT alone vs bridging therapy.","Anterior LVO at EVT centers","IVT plus EVT","234","mRS 0–2","EVT alone met noninferiority; stopped early.","Contributed to debate but not universal practice change.","Avoid IVT risks/delays.","Small, early stopped, noninferiority.","Regional selection.","Bridging IVT remains standard in many guidelines.","Zi et al. JAMA. 2021;325:234-243.",[]),
T("SKIP","2021","Stroke systems of care","LVO bridging-eligible","Direct EVT","Bridging thrombolysis","Can EVT alone skip alteplase?","LVO patients eligible for alteplase","IVT plus EVT","204","mRS 0–2","Did not demonstrate noninferiority of direct EVT.","Supports continuing IVT when eligible.","IVT may improve reperfusion/access.","Underpowered.","Japan-dose alteplase context.","Part of bridging evidence.","Suzuki et al. JAMA. 2021;325:244-253.",[]),
T("MR CLEAN-NO IV","2021","Stroke systems of care","LVO bridging-eligible","Direct EVT","Bridging thrombolysis","EVT alone vs IVT+EVT in comprehensive centers.","Anterior LVO eligible for IVT","IVT plus EVT","539","mRS at 90 days","EVT alone neither superior nor noninferior under trial criteria; verify exact wording.","Did not support omitting IVT routinely.","IVT may aid distal/microvascular reperfusion.","Noninferiority design.","Workflow and alteplase timing matter.","Supports bridging if no contraindication.","LeCouffe et al. N Engl J Med. 2021;385:1833-1844.",["MR CLEAN NO IV"]),
T("SWIFT DIRECT","2022","Stroke systems of care","LVO bridging-eligible","Direct EVT","Bridging thrombolysis","Direct EVT vs bridging with alteplase.","LVO eligible for IV alteplase","Alteplase plus EVT","408","mRS outcome/noninferiority","Direct EVT did not meet noninferiority; verify exact result.","Supports IVT before EVT when eligible.","Bridging may provide additional reperfusion.","Trial stopped early/underpowered concerns.","Selected comprehensive centers.","Part of evidence favoring not skipping IVT.","Fischer et al. Lancet. 2022; citation to verify.",[]),
T("DIRECT-SAFE","2022","Stroke systems of care","LVO bridging-eligible","Direct EVT","Bridging thrombolysis","Direct EVT vs bridging across regions.","LVO eligible for IVT and EVT","IVT plus EVT","293","mRS shift","Did not show noninferiority overall; possible regional differences.","Bridging IVT remains recommended for eligible patients.","Tests no-lytic workflow.","Underpowered; stopped early.","Heterogeneity by region/thrombolytic.","Informs direct-to-EVT debate.","Mitchell et al. Lancet. 2022; citation to verify.",["DIRECT SAFE"]),
T("BEST-MSU","2021","Stroke systems of care","Prehospital AIS","Mobile stroke unit","Mobile stroke unit","Does MSU improve outcomes via faster thrombolysis?","Suspected stroke managed by MSU vs EMS","Standard EMS","1047 treated analysis; verify exact","mRS/disability","MSU care improved functional outcomes among thrombolysis-eligible patients.","Supports MSU where available and feasible.","Earlier thrombolysis improves outcomes.","Resource intensive; urban geography.","Generalizability/cost-effectiveness.","Guideline support for MSU implementation.","Grotta et al. N Engl J Med. 2021;385:971-981.",["BEST MSU"]),
T("B_PROUD","2021","Stroke systems of care","Prehospital stroke","Mobile stroke unit","Mobile stroke unit","MSU dispatch effect on disability.","Suspected stroke in Berlin","Conventional ambulance",verify,"mRS/disability","MSU dispatch associated with better outcomes; verify exact design/results.","Supports MSU systems in dense urban areas.","Ultra-early treatment.","Nontraditional design/region-specific.","Resource and deployment limits.","Informs MSU recommendation.","Ebinger et al. JAMA. 2021;325:454-466.",["B-PROUD","BPROUD"])
];

// Add status-aware helpers
let detectedNames = new Set();
const byId = s => document.getElementById(s);

function normalize(s){return (s||"").toLowerCase().replace(/[–—]/g,"-").replace(/[^a-z0-9]+/g," ").trim();}
function trialMatched(trial, textNorm){
  const terms=[trial.name,...trial.aliases].filter(Boolean).map(normalize);
  return terms.some(term => term && textNorm.includes(term));
}
function uniqueValues(key){
  return [...new Set(trials.map(t=>t[key]).filter(Boolean))].sort();
}
function fillFilters(){
  const map=[["categoryFilter","category"],["conditionFilter","condition"],["interventionFilter","intervention"],["topicFilter","topic"]];
  map.forEach(([id,key])=>{
    const sel=byId(id);
    uniqueValues(key).forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;sel.appendChild(o);});
  });
}
function scanText(){
  const text=byId("sourceText").value || "";
  const textNorm=normalize(text);
  detectedNames.clear();
  trials.forEach(t=>{
    if(textNorm && trialMatched(t,textNorm)){ t.status="found in uploaded text"; detectedNames.add(t.name); }
    else { t.status="important trial not detected in text"; }
  });
  renderDetected(); renderTrials();
}
function renderDetected(){
  const found=trials.filter(t=>t.status==="found in uploaded text");
  const missing=trials.filter(t=>t.status!=="found in uploaded text");
  byId("foundCount").textContent=found.length;
  byId("missingCount").textContent=missing.length;
  byId("totalCount").textContent=trials.length;
  const top=[...found.slice(0,24),...missing.slice(0,24)];
  byId("detectedList").innerHTML = top.map(t=>`<div class="detectedItem ${t.status==='found in uploaded text'?'found':'missing'}"><strong>${t.name}</strong><br><small>${t.category}</small><br><span>${t.status}</span></div>`).join("") +
    (trials.length>top.length ? `<div class="detectedItem"><strong>More trials available below</strong><br><small>Use filters/search in the library.</small></div>`:"");
}
function currentFiltered(){
  const q=normalize(byId("searchBox").value);
  const cat=byId("categoryFilter").value, cond=byId("conditionFilter").value, intv=byId("interventionFilter").value, topic=byId("topicFilter").value;
  return trials.filter(t=>{
    const hay=normalize(Object.values(t).join(" "));
    return (!q || hay.includes(q)) && (!cat || t.category===cat) && (!cond || t.condition===cond) && (!intv || t.intervention===intv) && (!topic || t.topic===topic);
  });
}
function field(label,val){return `<p class="field"><strong>${label}</strong>${val||"verify exact number"}</p>`}
function card(t){
  const statusClass=t.status==="found in uploaded text"?"found":"missing";
  return `<article class="card">
    <div class="cardHeader" tabindex="0" role="button" aria-label="Open ${t.name}">
      <div class="badges"><span class="badge">${t.year}</span><span class="badge">${t.condition}</span><span class="badge ${statusClass}">${t.status}</span></div>
      <h3>${t.name}</h3>
      <p class="muted">${t.clinicalQuestion}</p>
    </div>
    <div class="cardBody">
      ${field("Clinical question",t.clinicalQuestion)}
      ${field("Stroke condition addressed",t.condition)}
      ${field("Guideline section where it is used",t.topic)}
      ${field("Population / inclusion criteria",t.population)}
      ${field("Intervention",t.intervention)}
      ${field("Comparator",t.comparator)}
      ${field("Sample size",t.sampleSize)}
      ${field("Primary outcome",t.primaryOutcome)}
      ${field("Main result",t.mainResult)}
      ${field("Practice-changing conclusion",t.conclusion)}
      ${field("Rationale",t.rationale)}
      ${field("Criticism",t.criticism)}
      ${field("Limitations",t.limitations)}
      ${field("How it changed clinical practice",t.practice)}
      ${field("Key reference",t.reference)}
    </div>
  </article>`;
}
function renderTrials(){
  const filtered=currentFiltered();
  const html=categories.map(cat=>{
    const list=filtered.filter(t=>t.category===cat);
    if(!list.length) return "";
    return `<section class="categoryBlock"><h3 class="categoryTitle">${cat} <span class="muted">(${list.length})</span></h3><div class="cards">${list.map(card).join("")}</div></section>`;
  }).join("");
  byId("trialContainer").innerHTML=html || `<p class="muted">No trials match the current filters.</p>`;
  document.querySelectorAll(".cardHeader").forEach(h=>{
    h.addEventListener("click",()=>h.closest(".card").classList.toggle("open"));
    h.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();h.closest(".card").classList.toggle("open");}});
  });
  renderReferences(filtered);
}
function renderReferences(list=currentFiltered()){
  byId("referenceList").innerHTML=list.map(t=>`<p><strong>${t.name}.</strong> ${t.reference}</p>`).join("");
}
function csvEscape(v){return `"${String(v??"").replaceAll('"','""')}"`;}
function makeCSV(list=currentFiltered()){
  const headers=["Trial name","Year published","Clinical question","Stroke condition addressed","Guideline section where it is used","Population / inclusion criteria","Intervention","Comparator","Sample size","Primary outcome","Main result","Practice-changing conclusion","Rationale","Criticism","Limitations","How it changed clinical practice","Key reference","Status"];
  const keys=["name","year","clinicalQuestion","condition","topic","population","intervention","comparator","sampleSize","primaryOutcome","mainResult","conclusion","rationale","criticism","limitations","practice","reference","status"];
  return [headers.map(csvEscape).join(","),...list.map(t=>keys.map(k=>csvEscape(t[k])).join(","))].join("\n");
}
function exportCSV(){
  const blob=new Blob([makeCSV()],{type:"text/csv;charset=utf-8"});
  const url=URL.createObjectURL(blob);
  const a=document.createElement("a");
  a.href=url; a.download="stroke_landmark_trials.csv"; a.click();
  URL.revokeObjectURL(url);
}
async function copyTable(){
  await navigator.clipboard.writeText(makeCSV());
  byId("copyTable").textContent="Copied!";
  setTimeout(()=>byId("copyTable").textContent="Copy table",1200);
}
byId("txtUpload").addEventListener("change", async e=>{
  const file=e.target.files[0]; if(!file) return;
  byId("sourceText").value=await file.text();
});
byId("scanBtn").addEventListener("click",scanText);
byId("clearBtn").addEventListener("click",()=>{byId("sourceText").value=""; detectedNames.clear(); trials.forEach(t=>t.status="built-in landmark database"); renderDetected(); renderTrials();});
["searchBox","categoryFilter","conditionFilter","interventionFilter","topicFilter"].forEach(id=>byId(id).addEventListener("input",renderTrials));
byId("exportCsv").addEventListener("click",exportCSV);
byId("copyTable").addEventListener("click",copyTable);
byId("printView").addEventListener("click",()=>window.print());

fillFilters();
renderDetected();
renderTrials();
